language: node_js
node_js:
  - "5.1"
  - "4.2"
install:
  - npm install -g typings tsc codeclimate-test-reporter
  - npm install

script:
  - npm test
  - codeclimate-test-reporter < ./coverage/lcov.info

# Allow Travis tests to run in containers.
sudo: false
